version: 3
services:
  db:
    image: postgres:11.5
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DBNAME}
    ports:
      - "5432:5432"
  api:
    build:
      context: api
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DBNAME=${DB_DBNAME}
